import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.lines import Line2D
import numpy as np
import os

# --- CONFIGURATION: UPDATE PATHS TO MATCH YOUR FOLDER ---
# Ensure these point to the CSVs generated by 'check_continuity.py'
BASE_DIR = r"../../"  # Relative path to validation folder

FILES = {
    'S1 ': os.path.join(BASE_DIR, 'Book1.csv'),
    'S2 ': os.path.join(BASE_DIR, 'Book2.csv'),
    'S3 ': os.path.join(BASE_DIR, 'Book3.csv'),
    'S4 ': os.path.join(BASE_DIR, 'Book5.csv'),
    'S5': os.path.join(BASE_DIR, 'Book6.csv')
}

# Column Names
TIME_COL = 'T_Start'        # Epoch Start Time
GAP_COL = 'True_Gap_Seconds' # The Calculated Gap

# --- PLOTTING SETUP ---
# Create 5 rows, 1 column. 
fig, axes = plt.subplots(nrows=5, ncols=1, figsize=(12, 16), constrained_layout=True)

# Flatten axes for easy iteration
axes = axes.flatten()

print("Generating Composite Continuity Figure...")

for i, (label, filepath) in enumerate(FILES.items()):
    ax = axes[i]
    print(f"Processing {label}...")
    
    # Error Handling: Check if file exists
    if not os.path.exists(filepath):
        ax.text(0.5, 0.5, f"FILE NOT FOUND:\n{filepath}", 
                transform=ax.transAxes, ha='center', color='red', fontweight='bold')
        continue

    try:
        # Load Data
        df = pd.read_csv(filepath)
        
        # Ensure Gap is calculated if missing (Safety check)
        if GAP_COL not in df.columns:
            df['Prev_End'] = df['T_End'].shift(1)
            df[GAP_COL] = df[TIME_COL] - df['Prev_End']
            
        # Convert Time
        dates = pd.to_datetime(df[TIME_COL], unit='s')
        gaps = df[GAP_COL]
        
        # Filter for significant events (> 1s or < -1s) to reduce noise
        # We ignore micro-gaps caused by rounding errors
        mask = (gaps > 1.0) | (gaps < -1.0)
        plot_dates = dates[mask]
        plot_gaps = gaps[mask]
        
        if len(plot_dates) == 0:
            ax.text(0.5, 0.5, "No Significant Gaps (>1s) Found", transform=ax.transAxes, ha='center', color='green')
        else:
            # Color logic: Red for Gaps (Data Loss), Orange for Overlaps (Clock Skew)
            colors = np.where(plot_gaps > 0, 'crimson', 'orange')
            
            # Scatter Plot
            ax.scatter(plot_dates, plot_gaps, c=colors, s=15, alpha=0.7, edgecolors='none')
            
        # --- SUBPLOT FORMATTING ---
        ax.set_title(label, loc='left', fontsize=11, fontweight='bold')
        ax.grid(True, which='both', linestyle=':', alpha=0.5)
        
        # Y-Axis: Log scale is mandatory to see 1s and 700,000s on same plot
        # Symlog allows plotting negative numbers (overlaps) on a log scale
        ax.set_yscale('symlog', linthresh=10)
        ax.set_ylabel('Gap Duration (s)', fontsize=9)
        
        # Reference Lines
        ax.axhline(0, color='black', linewidth=0.5)
        ax.axhline(3600, color='blue', linestyle=':', alpha=0.5) # 1-Hour Mark
        
        # X-Axis Date Formatting
        date_format = mdates.DateFormatter('%b %Y')
        ax.xaxis.set_major_formatter(date_format)
        ax.xaxis.set_major_locator(mdates.MonthLocator(interval=1))

    except Exception as e:
        ax.text(0.5, 0.5, f"Error loading data: {str(e)}", transform=ax.transAxes, ha='center', color='red')
        print(f"Error with {label}: {e}")

# --- GLOBAL FIGURE FORMATTING & LEGEND ---
plt.suptitle('Temporal Continuity & Data Loss Across Substation Fleet', fontsize=16, y=1.02)

# Create custom legend handles to explain the colors/lines globally
legend_elements = [
    Line2D([0], [0], marker='o', color='w', label='Data Gaps (>1s)', 
           markerfacecolor='crimson', markersize=8),
    Line2D([0], [0], marker='o', color='w', label='Overlaps (Clock Skew)', 
           markerfacecolor='orange', markersize=8),
    Line2D([0], [0], color='blue', linestyle=':', label='1-Hour Systemic Artifact')
]

# Add the legend to the figure (top right, outside the subplots)
fig.legend(handles=legend_elements, loc='upper right', bbox_to_anchor=(0.98, 1.015), ncol=3, fontsize=10)

# Save as High-Res Image for IEEE (300 DPI)
save_path = '../../05_Paper_Assets/Composite_Continuity_Figure.png'
# Ensure directory exists
os.makedirs(os.path.dirname(save_path), exist_ok=True)

plt.savefig(save_path, dpi=300, bbox_inches='tight')
print(f"Figure saved to {save_path}")
plt.show()